a = int(input("Enter value of a:"))
b = int(input("Enter the value of b:))
print("Addition:",a + b)
print("Substraction:",a - b)
print("Division:",a / b)
print("Multiplication:",a * b)
print("Floor Division:",a // b)
print("Power:",a ** b)
print("Modulus:,"a % b)
